'''
Created on Oct 22, 2012


@author: Kelvin
'''

import os
import errno
import sys


if __name__ == '__main__':
    
    # Refactor this using argparse
    # http://docs.python.org/dev/library/argparse.html
    
    if (len(sys.argv) == 2):
        project_name = sys.argv[1];
    else:
        raise "{projectname} required"

    project_dirs = (
            "/_templates",
            "/architecture",
            "/architecture/principles",            
            "/architecture/policies",            
            "/architecture/standards",
            "/architecture/specifications",
            "/architecture/patterns",                                    
            "/architecture/views",
            "/architecture/views/context",            
            "/architecture/views/component",
            "/architecture/views/network",
            "/architecture/views/security",
            "/architecture/views/security/at_rest",
            "/architecture/views/security/in_motion",
            "/architecture/views/data",
            "/architecture/views/integrations",
            "/architecture/views/integrations/batch",
            "/architecture/views/integrations/batch/inbound",
            "/architecture/views/integrations/batch/outbound",
            "/architecture/views/integrations/services",
            "/architecture/views/integrations/services/consuming",
            "/architecture/views/integrations/services/producing",            
            "/architecture/presentations",
            "/change_management",
            "/change_management/change_requests",
            "/change_management/change_requests/10_submitted",
            "/change_management/change_requests/20_approved",
            "/change_management/change_requests/30_scheduled",
            "/change_management/change_requests/40_implemented",
            "/change_management/change_requests/50_rejected",
            "/change_management/change_requests/60_deferred",
            "/change_management/newsletters",
            "/contracts",
            "/contracts/vendors",            
            "/contracts/vendors/XYZ",            
            "/team_journals",
            "/team_journals/user_a",
            "/team_journals/user_b",
            "/team_journals/user_c",                        
            "/data",
            "/data/dictionary",
            "/data/governance",
            "/data/domains",    
            "/data/domains/enterprise",
            "/data/domains/enterprise/models",            
            "/data/domains/enterprise/cannonical_schema",
            "/data/domains/enterprise/scripts",            
            "/data/domains/applications",                        
            "/data/domains/apps/XYZ",
            "/data/domains/apps/XYZ/model",
            "/data/domains/apps/XYZ/schema",                             
            "/data/domains/apps/XYZ/scripts",            
            "/deployment",
            "/deployment/schedule",
            "/deployment/presentations",
            "/deployment/dependencies",
            "/deployment/procedures",
            "/deployment/scripts",            
            "/design",
            "/design/reviews",
            "/design/reviews/ARB",
            "/design/reviews/DBR",                                    
            "/design/reviews/IDR",
            "/design/reviews/IDR/NON_PROD", 
            "/design/reviews/IDR/PROD",
            "/design/reviews/wall_walks",                                         
            "/design/reviews/security",            
            "/design/AS_IS",
            "/design/AS_IS/applications",                        
            "/design/AS_IS/applications/XYZ",
            "/design/AS_IS/conversions/",
            "/design/AS_IS/disaster_recovery/",            
            "/design/AS_IS/integrations",
            "/design/AS_IS/integrations/batch",
            "/design/AS_IS/integrations/batch/inbound",
            "/design/AS_IS/integrations/batch/outbound",
            "/design/AS_IS/integrations/services",
            "/design/AS_IS/integrations/services/consuming",
            "/design/AS_IS/integrations/services/producing",            
            "/design/AS_IS/requirements",
            "/design/AS_IS/requirements/business",            
            "/design/AS_IS/requirements/NFRs",            
            "/design/AS_IS/reports",
            "/design/AS_IS/security",            
            "/design/AS_IS/user_interface",
            "/design/TO_BE",
            "/design/TO_BE/applications",                        
            "/design/TO_BE/applications/XYZ",            
            "/design/TO_BE/conversions",
            "/design/TO_BE/disaster_recovery",                             
            "/design/TO_BE/integrations",
            "/design/TO_BE/integrations/batch",
            "/design/TO_BE/integrations/batch/inbound",
            "/design/TO_BE/integrations/batch/outbound",
            "/design/TO_BE/integrations/services",
            "/design/TO_BE/integrations/services/consuming",
            "/design/TO_BE/integrations/services/producing",
            "/design/TO_BE/requirements",
            "/design/TO_BE/requirements/business",            
            "/design/TO_BE/requirements/NFRs",            
            "/design/TO_BE/reviews",
            "/design/TO_BE/reports",
            "/design/TO_BE/security",            
            "/design/TO_BE/user_interface",            
            "/infrastructure",
            "/infrastructure/diagrams",
            "/infrastructure/environments",
            "/infrastructure/environments/10_dev",
            "/infrastructure/environments/20_sit",
            "/infrastructure/environments/30_pit",
            "/infrastructure/environments/40_prod",
            "/infrastructure/nas",
            "/infrastructure/nas/secure",
            "/infrastructure/network",
            "/infrastructure/security",            
            "/operations",
            "/operations/monitoring",
            "/operations/alerting",
            "/operations/batch",            
            "/operations/batch/file_transfers",
            "/operations/batch/reporting",            
            "/operations/batch/dashboards",            
            "/operations/batch/runbooks",
            "/operations/batch/schedules",
            "/pmo",
            "/pmo/budgets",
            "/pmo/charter",
            "/pmo/contacts",
            "/pmo/dashboards",            
            "/pmo/defect_tracking",
            "/pmo/expense_reports",
            "/pmo/memos",
            "/pmo/project_plans",
            "/pmo/org_charts",
            "/pmo/presentations",
            "/pmo/reporting",            
            "/pmo/resources",
            "/pmo/releases",
            "/pmo/sprint_planning",
            "/pmo/sprints",
            "/pmo/sprints/sprint_0",
            "/pmo/sprints/sprint_1",
            "/pmo/sprints/sprint_2",
            "/pmo/status_reports",
            "/references",
            "/references/standards",
            "/references/policies",
            "/references/specifications",
            "/references/third_party",            
            "/requirements",
            "/requirements/functional",
            "/requirements/nfrs",
            "/requirements/user_stories",
            "/time_tracking",
            "/testing",
            "/testing/00_test_plans",
            "/testing/10_integration",
            "/testing/20_system",
            "/testing/30_performance",
            "/testing/30_performance/online",
            "/testing/30_performance/batch",
            "/testing/40_user_acceptance",
            "/training",
            "/training/users",
            "/training/users/docs",            
            "/training/users/presentations",
            "/training/admins",
            "/training/admins/docs",            
            "/training/admins/presentations",
            "/training/train_the_trainer",
            "/training/train_the_trainer/docs",            
            "/training/train_the_trainer/presentations",
            "/vendors"
            );
    try:
        os.mkdir(project_name);
        for sub_dir in project_dirs:
            os.mkdir(project_name + sub_dir);
    except OSError as exception:
        if exception.errno != errno.EEXIST:
            raise
